#!/usr/bin/env python3
"""BloomTunes Studio v0.6 — docks Meditation Mode into the normal window layout.

This keeps v0.5 behavior intact, including meditation playback cleanup, while
moving the meditation controls out of the floating overlay and into the packed
Tk layout so they cannot cover sequencer controls.
"""
from __future__ import annotations

import tkinter as tk

import bloomtunes_studio_v0_5 as previous


class Studio(previous.Studio):
    def __init__(self):
        super().__init__()
        self.title("BloomTunes Studio v0.6 — Sequencer + Docked Meditation Mode")
        self._dock_meditation_panel()

    def _dock_meditation_panel(self):
        """Move the v0.5 floating meditation panel into the packed layout."""
        children = list(self.winfo_children())

        # v0.5 creates Meditation Mode as the only direct child managed by
        # `place()`. Find it by geometry manager rather than depending on an
        # autogenerated Tk widget name.
        meditation = next((w for w in children if w.winfo_manager() == "place"), None)
        if meditation is None:
            return

        meditation.place_forget()

        # Base v0.4 packs: header, navigation, track buttons, track controls,
        # piano roll, FX rack. Dock meditation immediately before the track
        # button row so it lives with the top controls instead of overlapping
        # them. Anchor right to preserve the requested compact top-right feel.
        packed = [w for w in self.winfo_children() if w is not meditation and w.winfo_manager() == "pack"]
        before = packed[2] if len(packed) >= 3 else None

        opts = dict(anchor="e", padx=8, pady=(4, 2))
        if before is not None:
            meditation.pack(before=before, **opts)
        else:
            meditation.pack(**opts)


if __name__ == "__main__":
    Studio().mainloop()
