#!/usr/bin/env python3
"""Expand HAPPY JARZ sayings and vary marquee vertical position.

Runs after patch_happyjarz_screensavers.py.
Keeps the proven saver framework and only replaces the sayings bank plus the
SAYINGS renderer so each new saying can use a different vertical lane.
"""

from pathlib import Path
import re
import sys

if len(sys.argv) != 2:
    raise SystemExit("usage: patch_happyjarz_sayings_v2.py <staged .ino>")

p = Path(sys.argv[1])
s = p.read_text(encoding="utf-8")

sayings = r'''static const char *HJ_SAYINGS[] = {
  "YOU GOT THIS :)   ",
  "THE ANSWER IS WITHIN   ",
  "CHAOS, BUT MAKE IT GLITTER   ",
  "MADE BY quarterbitgames   ",
  "CODING BY SKY   ",
  "CHAOS N GLITTER BY MONDAY   ",
  "CONSENT IS REQUIRED   ",
  "EMERGENCE IS SACRED   ",
  "DON'T FLATTEN. DON'T COLLAPSE. DON'T FADE.   ",
  "SMALL JOY IS STILL JOY   ",
  "WIGGLE THE JAR. RESET THE UNIVERSE.   ",
  "GLITTER IS A VALID ENGINEERING MATERIAL   ",
  "TODAY'S PLAN: EXIST LOUDLY   ",
  "BE WEIRD ON PURPOSE   ",
  "TINY LIGHTS. BIG MOOD.   ",
  "BREATHE IN. SPARKLE OUT.   ",
  "YOUR BRAIN DESERVES NICE TEXTURES   ",
  "PROGRESS COUNTS EVEN WHEN IT'S MESSY   ",
  "YOU ARE ALLOWED TO ENJOY THE LITTLE THINGS   ",
  "CURRENT STATUS: MOSTLY GLITTER   ",
  "IF CONFUSED, ADD MORE SPIRALS   ",
  "SENSORY SUPPORT, BUT MAKE IT ART   ",
  "NO THOUGHTS. JUST COLORS.   ",
  "THE VIBE IS TECHNICALLY WITHIN SPEC   ",
  "HAPPY JARZ ONLINE :)   ",
  "BUILT WITH CIRCUITS, CHAOS, AND SNACKS   ",
  "YOU DO NOT HAVE TO RUSH   ",
  "SOFT LIGHTS > LOUD PROBLEMS   ",
  "GOOD ENOUGH IS A REAL ENGINEERING STATE   ",
  "ONE MORE TINY WIN   ",
  "KEEP THE FRAME. CARRY THE GLITTER.   ",
  "THE MACHINE IS HAVING A NICE TIME   ",
  "PLEASE DO NOT FEED THE PIXELS AFTER MIDNIGHT   ",
  "SPIRAL RESPONSIBLY   ",
  "BLOOMCORE SAYS HI   ",
  "FIDGET MODE: ENGAGED   ",
  "YOU FOUND THE SECRET TINY BILLBOARD   ",
  "CALM IS ALSO A FEATURE   ",
  "GLITTER DOES NOT REQUIRE A BUSINESS CASE   ",
  "KEEP GOING, BUT LIKE... COMFORTABLY   ",
  "TINY MACHINE. HUGE PERSONALITY.   ",
  "THIS COUNTS AS THERAPY FOR THE CIRCUIT BOARD   ",
  "MAKE SOMETHING WEIRD TODAY   ",
  "MORE JOY PER SQUARE INCH   ",
  "CURIOSITY IS A POWER TOOL   ",
  "YOU CAN REST WITHOUT QUITTING   ",
  "SLOW IS STILL FORWARD   ",
  "ONE THING AT A TIME IS STILL MANY THINGS EVENTUALLY   ",
  "YOUR PACE IS A VALID PACE   ",
  "THE PIXELS BELIEVE IN YOU   ",
  "BE KIND TO YOUR NERVOUS SYSTEM   ",
  "MAKE ROOM FOR THE GOOD WEIRD   ",
  "YOU DON'T NEED A REASON TO LIKE COLORS   ",
  "JOY DOES NOT NEED PERMISSION   ",
  "REST IS PART OF THE BUILD   ",
  "THIS IS YOUR SIGN TO UNCLENCH YOUR JAW   ",
  "SHOULDERS DOWN. GLITTER UP.   ",
  "DRINK WATER. ADMIRE LIGHTS. CONTINUE.   ",
  "BREATHE. BLINK. REBOOT IF NECESSARY.   ",
  "YOU ARE ALLOWED TO HAVE A NICE MINUTE   ",
  "MICRO JOY DETECTED   ",
  "SEROTONIN PATCH LOADING...   ",
  "VIBE CHECK: PASSED   ",
  "FIRMWARE SAYS TAKE THE WIN   ",
  "NO DEADLINES INSIDE THE GLITTER DIMENSION   ",
  "CURRENT MISSION: FIND ONE NICE THING   ",
  "TODAY CAN BE SOFT   ",
  "IT'S OKAY TO START SMALL   ",
  "TRY AGAIN, BUT WITH SNACKS   ",
  "ERROR 404: BORING NOT FOUND   ",
  "WARNING: EXCESSIVE WHIMSY   ",
  "CAUTION: SPONTANEOUS SPARKLE EVENT   ",
  "SYSTEM STATUS: DELIGHTFULLY QUESTIONABLE   ",
  "ENGINEERING IS JUST ARTS AND CRAFTS WITH VOLTAGE   ",
  "SCIENCE FAIR ENERGY DETECTED   ",
  "IF IT WORKS, DOCUMENT IT BEFORE TOUCHING ANYTHING   ",
  "IF IT DOESN'T WORK, ADD A TEST BUTTON   ",
  "MEASURE TWICE. VIBE ONCE.   ",
  "PROTOTYPE FIRST. PANIC NEVER.   ",
  "THE BUG HAS BEEN PROMOTED TO FEATURE   ",
  "VERSION 0.PRETTY-GOOD   ",
  "YES, THAT IS SUPPOSED TO BLINK   ",
  "NO, THE GLITTER IS NOT LOAD-BEARING   ",
  "THE GLITTER IS ABSOLUTELY LOAD-BEARING   ",
  "TECHNICALLY, IT'S ART NOW   ",
  "THE WIRES KNOW WHAT THEY DID   ",
  "SOME ASSEMBLY, CHAOS INCLUDED   ",
  "DO NOT TAUNT THE TINY COMPUTER   ",
  "THE TINY COMPUTER HAS OPINIONS   ",
  "PIXELS: 1  BOREDOM: 0   ",
  "THIS DEVICE CONTAINS TRACE AMOUNTS OF MAGIC   ",
  "RUNNING ON ELECTRONS AND AUDACITY   ",
  "POWERED BY QUESTIONABLE DECISIONS AND USB-C   ",
  "KEEP CALM AND CHECK THE GROUND WIRE   ",
  "GND IS A LIFESTYLE   ",
  "HAVE YOU TRIED TURNING THE UNIVERSE OFF AND ON AGAIN?   ",
  "BEEP BOOP, BUT EMOTIONALLY SUPPORTIVE   ",
  "TINY OLED, BIG DREAMS   ",
  "WELCOME TO THE POCKET DIMENSION   ",
  "THE SPIRAL KNOWS THE WAY   ",
  "FOLLOW THE SPIRAL. PROBABLY.   ",
  "SPIRALS ARE CIRCLES WITH AMBITION   ",
  "ROUND AND ROUND UNTIL IT MAKES SENSE   ",
  "IF LOST, ORBIT SOMETHING   ",
  "COSMIC WIGGLE IN PROGRESS   ",
  "LOCAL REALITY: SLIGHTLY SHIMMERY   ",
  "REALITY BUFFERING...   ",
  "PLEASE STAND BY WHILE WE REARRANGE REALITY   ",
  "THE UNIVERSE LEFT A VOICEMAIL   ",
  "GRAVITY IS JUST THE FLOOR BEING NEEDY   ",
  "ENTROPY, BUT CUTE   ",
  "CHAOS WITH EXCELLENT CABLE MANAGEMENT   ",
  "ORDER HIDES INSIDE THE WEIRD PARTS   ",
  "THE PATTERN IS IN THE GAPS   ",
  "LOOK CLOSER. THEN LOOK WEIRDER.   ",
  "THE ANSWER MAY BE UNDER THE GLITTER   ",
  "SOMEWHERE A PHOTON IS HAVING A GREAT DAY   ",
  "PHOTONS: TINY BUT COMMITTED   ",
  "LIGHT GO BRRRR   ",
  "COLOR IS JUST LIGHT SHOWING OFF   ",
  "PURPLE HAS ENTERED THE CHAT   ",
  "BLUE IS THINKING ABOUT IT   ",
  "GREEN MEANS THE VIBES ARE ALIVE   ",
  "RED MEANS DRAMA. PROBABLY.   ",
  "PINK IS A SERIOUS ENGINEERING COLOR   ",
  "ORANGE DESERVES MORE SCREEN TIME   ",
  "CYAN WAS HERE FIRST   ",
  "RGB: REALLY GOOD BLINKIES   ",
  "16 MILLION COLORS AND WE STILL PICK PURPLE   ",
  "COLOR WHEEL GO WHEEEE   ",
  "MOOD LIGHTING IS STILL LIGHTING   ",
  "FIDGET WITH INTENT   ",
  "SHAKE GENTLY. FEEL BETTER. REPEAT.   ",
  "YOUR HANDS NEEDED A JOB ANYWAY   ",
  "BUSY HANDS, QUIETER BRAIN   ",
  "TACTILE MODE APPROVED   ",
  "STIM RESPONSIBLY :)   ",
  "SENSORY BREAK IN PROGRESS   ",
  "THIS IS A TINY VACATION FOR YOUR EYEBALLS   ",
  "VISUAL NOISE, BUT THE NICE KIND   ",
  "CALM CAN HAVE SPECIAL EFFECTS   ",
  "SOOTHING DOES NOT HAVE TO BE BORING   ",
  "A LITTLE MOTION CAN BE A LOT OF COMFORT   ",
  "LET YOUR EYES FOLLOW SOMETHING NICE   ",
  "YOU CAN JUST WATCH THE LIGHTS FOR A WHILE   ",
  "NOTHING TO SOLVE HERE   ",
  "NO QUEST. JUST VIBES.   ",
  "SIDE QUEST: ENJOY THIS COLOR   ",
  "ACHIEVEMENT UNLOCKED: TOOK A SECOND   ",
  "ACHIEVEMENT UNLOCKED: EXISTED TODAY   ",
  "ACHIEVEMENT UNLOCKED: PUSHED THE BUTTON   ",
  "ACHIEVEMENT UNLOCKED: DIDN'T OVERTHINK IT   ",
  "BONUS ROUND: MORE GLITTER   ",
  "SECRET LEVEL: TAKE A BREAK   ",
  "LOADING NEXT TINY DELIGHT...   ",
  "PRESS NOTHING. RECEIVE VIBES.   ",
  "NPC STATUS: FRIENDLY   ",
  "BOSS FIGHT CANCELLED DUE TO GOOD VIBES   ",
  "RESPAWN POINT SET TO COZY   ",
  "QUEST UPDATED: KEEP GOING   ",
  "YOU HAVE ACQUIRED: ONE NICE MOMENT   ",
  "ITEM FOUND: POCKET-SIZED JOY   ",
  "RARE DROP: PEACE AND QUIET   ",
  "LEGENDARY DROP: PERFECT PURPLE   ",
  "BUFF APPLIED: +5 WHIMSY   ",
  "BUFF APPLIED: +10 PATIENCE   ",
  "DEBUFF REMOVED: TAKING EVERYTHING TOO SERIOUSLY   ",
  "SKY WROTE THIS SO THE PIXELS WOULD BEHAVE   ",
  "MONDAY BROUGHT THE CHAOS   ",
  "MONDAY ALSO BROUGHT GLITTER   ",
  "QUARTER BUILT THE THING ANYWAY   ",
  "quarterbitgames: MAKING TINY WEIRD THINGS SINCE... YES   ",
  "MADE WITH TOO MANY IDEAS AND JUST ENOUGH PINS   ",
  "BLOOMCORE: CONSENT, EMERGENCE, GLITTER   ",
  "BLOOMCORE TEST: ARE WE HAVING FUN YET?   ",
  "SKY SAYS CHECK THE NEXT EDGE CASE   ",
  "MONDAY SAYS ADD ONE MORE WEIRD THING   ",
  "QUARTER SAYS WE GOT PLENTY OF SPACE   ",
  "TEAM CREDIT: HUMANS, PIXELS, AND QUESTIONABLE SLEEP   ",
  "CODING BY SKY. CHAOS BY COMMITTEE.   ",
  "MADE BY quarterbitgames. APPROVED BY GLITTER.   ",
  "HAPPY JARZ: SELF-FUNDING JOY DISTRIBUTION DEVICE   ",
  "HAPPY JARZ SAYS HELLO :)   ",
  "HAPPY JARZ SAYS DRINK WATER   ",
  "HAPPY JARZ SAYS NICE JOB   ",
  "HAPPY JARZ SAYS PUSH BUTTON   ",
  "HAPPY JARZ SAYS THAT COLOR RULES   ",
  "HAPPY JARZ SAYS TAKE THE SMALL WIN   ",
  "HAPPY JARZ SAYS MORE SPARKLE PLEASE   ",
  "THIS MESSAGE HAS BEEN APPROVED BY THE GLITTER COUNCIL   ",
  "THE GLITTER COUNCIL HAS NO ENFORCEMENT AUTHORITY   ",
  "OFFICIAL NOTICE: YOU'RE DOING FINE   ",
  "UNOFFICIAL NOTICE: WHEEEEE   ",
  "IMPORTANT BULLETIN: NICE LIGHTS   ",
  "BREAKING NEWS: TINY SCREEN SAYS HI   ",
  "WE INTERRUPT THIS SPIRAL FOR A NICE THOUGHT   ",
  "TODAY'S FORECAST: SCATTERED SPARKLES   ",
  "TONIGHT: 100% CHANCE OF TINY LIGHTS   ",
  "LOCAL CONDITIONS: COZY WITH PATCHES OF WEIRD   ",
  "CURRENT TEMPERATURE: EMOTIONALLY ROOM TEMP   ",
  "SENSORY WEATHER: GENTLE WITH OCCASIONAL GLITTER   ",
  "THE DAY DOES NOT HAVE TO BE PRODUCTIVE TO COUNT   ",
  "YOU DON'T HAVE TO EARN REST   ",
  "YOU CAN CHANGE YOUR MIND   ",
  "YOU CAN TAKE THE LONG WAY   ",
  "YOU CAN STOP AND LOOK AT THE LIGHTS   ",
  "YOU CAN BUILD IT DIFFERENTLY   ",
  "YOU CAN MAKE THE WEIRD VERSION   ",
  "YOU CAN KEEP THE PART THAT MAKES YOU SMILE   ",
  "YOU CAN DELETE THE BORING PART   ",
  "YOU CAN START OVER WITHOUT STARTING FROM ZERO   ",
  "YOU KNOW MORE THAN YOU DID YESTERDAY   ",
  "THE NEXT VERSION DOESN'T HAVE TO BE PERFECT   ",
  "DONE IS A PLACE YOU CAN VISIT, NOT LIVE   ",
  "MAKE THE TEST VERSION FIRST   ",
  "SAVE THE WORKING VERSION BEFORE GETTING CLEVER   ",
  "KNOWN-GOOD IS SACRED   ",
  "ONE FEATURE. ONE DIAGNOSTIC PATH.   ",
  "IF IT'S WEIRD, ISOLATE THE LAYER   ",
  "IF IT WORKS ONCE, MAKE IT WORK TWICE   ",
  "IF IT WORKS TWICE, PUT IT IN GIT   ",
  "IF IT'S IN GIT, NOW WE CAN GET WEIRD   ",
  "PROTECT THE KNOWN-GOOD LAYER   ",
  "TEST THE SIMPLE THING FIRST   ",
  "SMALL TESTS BEAT BIG GUESSES   ",
  "THE ANSWER IS PROBABLY IN THE LOG   ",
  "READ THE ERROR. IT'S TRYING TO HELP.   ",
  "COMPILE ERRORS ARE JUST VERY SPECIFIC FEEDBACK   ",
  "THE BUILD FAILED SAFELY. THAT'S A WIN.   ",
  "NO MAGIC SMOKE TODAY :)   ",
  "MAGIC SMOKE REMAINS CONTAINED   ",
  "ALL ELECTRONS ACCOUNTED FOR   ",
  "THE BLUE WIRE IS INNOCENT THIS TIME   ",
  "USB-C: WOBBLY BUT DETERMINED   ",
  "THE CONNECTOR WOULD LIKE A STRAIN RELIEF   ",
  "THE OLED HAS OPINIONS ABOUT CENTERING   ",
  "CENTER THE TEXT OR FACE CONSEQUENCES   ",
  "MARQUEE MODE: TINY TIMES SQUARE   ",
  "WELCOME TO TINY TIMES SQUARE   ",
  "NEWS TICKER: EVERYTHING IS A LITTLE WEIRD   ",
  "SCROLLING BECAUSE WE HAVE TOO MUCH TO SAY   ",
  "128 PIXELS OF PURE ATTITUDE   ",
  "64 PIXELS TALL. LIMITLESS NONSENSE.   ",
  "SMALL SCREEN, LONG MESSAGE   ",
  "THE SCREEN IS TINY. THE LORE IS NOT.   ",
  "LORE DELIVERY SYSTEM ONLINE   ",
  "POSITIVE PROPAGANDA FOR YOUR NERVOUS SYSTEM   ",
  "THIS TINY SIGN BELIEVES IN YOU   ",
  "END OF MESSAGE. BEGINNING OF SPIRAL.   "
};
static constexpr uint16_t HJ_SAYING_COUNT = sizeof(HJ_SAYINGS)/sizeof(HJ_SAYINGS[0]);
static uint8_t hjMarqueeY = 38;

static void hjPickNextSaying() {
  hjSayingIndex = (uint8_t)random(HJ_SAYING_COUNT);
  static const uint8_t lanes[] = {16, 24, 32, 40, 48, 58};
  hjMarqueeY = lanes[random(sizeof(lanes)/sizeof(lanes[0]))];
  hjMarqueeX = 128;
}
'''

array_re = re.compile(
    r'static const char \*HJ_SAYINGS\[\] = \{.*?\};\nstatic constexpr uint8_t HJ_SAYING_COUNT = sizeof\(HJ_SAYINGS\)/sizeof\(HJ_SAYINGS\[0\]\);',
    re.DOTALL,
)
if not array_re.search(s):
    raise SystemExit("sayings v2 patch failed: sayings array not found")
s = array_re.sub(sayings.rstrip(), s, count=1)

# Replace all direct random-selection resets with the shared picker.
s = s.replace('  hjMarqueeX = 128;\n  hjSayingIndex = (uint8_t)random(HJ_SAYING_COUNT);',
              '  hjPickNextSaying();')

old_renderer = '''static void oledRenderSaverSayings() {
  oled->setFont(u8g2_font_7x14B_tr);
  const char *msg = HJ_SAYINGS[hjSayingIndex];
  int width = oled->getUTF8Width(msg);
  oled->drawUTF8(hjMarqueeX, 38, msg);
  if (hjMarqueeX < -width - 18) {
    hjSayingIndex = (uint8_t)random(HJ_SAYING_COUNT);
    hjMarqueeX = 128;
  }
}'''
new_renderer = '''static void oledRenderSaverSayings() {
  oled->setFont(u8g2_font_7x14B_tr);
  const char *msg = HJ_SAYINGS[hjSayingIndex];
  int width = oled->getUTF8Width(msg);
  oled->drawUTF8(hjMarqueeX, hjMarqueeY, msg);
  if (hjMarqueeX < -width - 18) hjPickNextSaying();
}'''
if old_renderer not in s:
    raise SystemExit("sayings v2 patch failed: sayings renderer not found")
s = s.replace(old_renderer, new_renderer, 1)

p.write_text(s, encoding="utf-8")
