#!/usr/bin/env python3
"""Undo the mistaken HOME line-3 stat move and repair STATS menu scrolling.

Final intent:
- HOME returns to the prior behavior from patch_home_name_stat_ticker.py:
    line 1 pet art/sayings ticker
    line 2 pet name/stat ticker
    line 3 selected action
    line 4 controls/status
- Main MENU has 5 items and scrolls through all of them:
    FEED / TREAT / SLOT / EDIT|CREATE PET / STATS
- When STATS is selected, it is visible on menu line 3:
    SLOT
    EDIT PET
   >STATS
    footer on line 4
"""
from pathlib import Path
import re
import sys

UNDO_MARKER = "// BLOOMPETZ_UNDO_HOME_LINE3_AND_STATS_MENU_FIX_V1"
MOVE_MARKER = "// BLOOMPETZ_HOME_STATS_LINE3_V1"
STATS_MARKER = "// BLOOMPETZ_STATS_BROWSER_V1"


def replace_function(text: str, signature: str, new_func: str) -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"Function not found: {signature}")
    brace = text.find('{', start)
    if brace < 0:
        raise SystemExit(f"Opening brace not found for: {signature}")
    depth = 0
    in_str = False
    esc = False
    end = None
    for i in range(brace, len(text)):
        ch = text[i]
        if in_str:
            if esc:
                esc = False
            elif ch == '\\':
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    if end is None:
        raise SystemExit(f"Unbalanced function: {signature}")
    return text[:start] + new_func + text[end:]


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: patch_undo_line3_and_fix_stats_menu.py <bloompetz_v0_1.ino>")

    ino = Path(sys.argv[1]).expanduser().resolve()
    s = ino.read_text()

    if UNDO_MARKER in s:
        print("HOME line-3 undo + STATS menu fix already applied.")
        return

    # Undo only the mistaken HOME-line-3 patch if it was applied.
    if MOVE_MARKER in s:
        old_sig = "static String homeLine3Ticker(const PetSave &p, const String &normalLine3) {"
        if old_sig in s:
            s = s.replace(old_sig, "static String homeLine2Ticker(const PetSave &p) {", 1)
            s = s.replace("  if (!homeNameStatShowingStat) return normalLine3;",
                          "  if (!homeNameStatShowingStat) return String(p.name);", 1)

        # Restore the generated drawHome call from:
        # renderDisplay(X, String(p.name), homeLine3Ticker(p, line3), Y)
        # to:
        # renderDisplay(X, homeLine2Ticker(p), line3, Y)
        dm = re.search(r"static void drawHome\(\) \{(?P<body>.*?)\n\}", s, re.S)
        if not dm:
            raise SystemExit("Could not isolate drawHome() while undoing HOME line-3 patch")
        body = dm.group("body")
        pat = re.compile(
            r"renderDisplay\((?P<l1>[^;\n]+?),\s*String\(p\.name\),\s*"
            r"homeLine3Ticker\(p,\s*(?P<l3>[^\)]+)\),\s*(?P<l4>[^;\n]+)\);"
        )
        mm = pat.search(body)
        if not mm:
            raise SystemExit("Could not find mistaken HOME line-3 render call")
        restored = (
            f"renderDisplay({mm.group('l1').strip()}, homeLine2Ticker(p), "
            f"{mm.group('l3').strip()}, {mm.group('l4').strip()});"
        )
        body = body[:mm.start()] + restored + body[mm.end():]
        s = s[:dm.start('body')] + body + s[dm.end('body'):]
        s = s.replace(MOVE_MARKER + "\n", "", 1)
        s = s.replace(MOVE_MARKER, "", 1)

    if STATS_MARKER not in s:
        raise SystemExit(
            "Stats browser patch is not present in this local sketch. "
            "Apply patch_add_stats_browser.py first, then run this repair."
        )

    # Force a deterministic 5-item scrolling menu. Three menu rows + footer.
    draw_menu = r'''static void drawMainMenu() {
  // Five items, three visible rows. Keep the selected item visible.
  // For the final item (STATS), the window is SLOT / EDIT PET / STATS,
  // placing STATS on OLED line 3 exactly as intended.
  uint8_t first;
  if (mainMenuIndex <= 1) first = 0;
  else if (mainMenuIndex == 2) first = 1;
  else first = 2;

  String rows[3];
  for (uint8_t r=0; r<3; ++r) {
    uint8_t idx = first + r;
    rows[r] = String(idx == mainMenuIndex ? "> " : "  ") + mainMenuLabel(idx);
  }
  renderDisplay(rows[0], rows[1], rows[2], "A ENTER B BACK");
}'''
    s = replace_function(s, "static void drawMainMenu()", draw_menu)

    # Repair navigation arithmetic if an older 4-item MENU handler survived locally.
    # Prefer replacing the mainMenuIndex versions generated by the stats patch.
    s = re.sub(r"mainMenuIndex\s*=\s*\(mainMenuIndex\s*\+\s*\d+\)\s*%\s*\d+\s*;",
               "mainMenuIndex=(mainMenuIndex+4)%5;", s, count=1)
    # DOWN is normally the next occurrence; normalize it separately by matching its branch.
    s = re.sub(r"else\s+if\s*\(in==DOWN\)\s*mainMenuIndex\s*=\s*\(mainMenuIndex\s*\+\s*\d+\)\s*%\s*\d+\s*;",
               "else if(in==DOWN) mainMenuIndex=(mainMenuIndex+1)%5;", s, count=1)

    # Verify the STATS action is reachable.
    if "mainMenuIndex==4" not in s or "STATS_BROWSE" not in s:
        raise SystemExit("STATS action is not wired to menu index 4; refusing to leave a half-fixed menu")

    # Add our marker near the stats browser marker.
    s = s.replace(STATS_MARKER, STATS_MARKER + "\n" + UNDO_MARKER, 1)

    ino.write_text(s)
    print(f"Undid mistaken HOME line-3 change and repaired STATS menu in {ino}")
    print("HOME restored: line 2 name/stat ticker, line 3 action.")
    print("MENU repaired: DOWN reaches STATS; selected STATS is displayed on menu line 3.")


if __name__ == "__main__":
    main()
